This creates a long file with clips glued together and 25 sample all zero buffers between them

It's designed for a process that just grabs a window instead of using a prepared frame (since that creates massive data duplication)

In [1]:
import numpy as np
import pandas as pd
import librosa
import librosa.display
from IPython.display import Audio, display
import numpy as np

import os
import time
import cmath

In [2]:
# Constants and settings
DTYPE = 'float32'

# Number of all zero samples between clips
# TODO - not using pads at all, on assumption that the samples have a bit of buffer at start and end
# PAD_SIZE = 1 

# cqt related
FFT_BINS = 768 # function of items below
HOP_LENGTH = 128 # Required for good cqt results

# stft values
N_FFT = 1024 # 512 recommended for speech, music typically 2048

# cqt values
BINS_PER_OCTAVE = 12 * 8
FMIN = librosa.note_to_hz('C1')
OCTAVES = 8

In [3]:
# Idea here is that we operate on magnitude, and will just use phase from the original noisy sample

def rebuild_fft(output, original_fft):
    vphase = np.vectorize(cmath.phase)
    o_phase = vphase(original_fft)
    mag = output.T
    vrect = np.vectorize(cmath.rect)
    return vrect(mag, o_phase)
    
# May not actually use this - may want to just pass a reduced view and then add this back to get right shape
def filter(cqt):
    cqt[0:BINS_PER_OCTAVE,:] = 0
    return cqt

def get_ft(wav):
    c = librosa.cqt(wav, hop_length=HOP_LENGTH, fmin=FMIN, n_bins=OCTAVES*BINS_PER_OCTAVE, bins_per_octave=BINS_PER_OCTAVE)
    #c = librosa.stft(wav, hop_length=HOP_LENGTH, n_fft=N_FFT)
    return c

def inv_ft(ft):
    return librosa.icqt(ft, hop_length=HOP_LENGTH, fmin=FMIN, bins_per_octave=BINS_PER_OCTAVE)
    #return librosa.istft(ft, hop_length=HOP_LENGTH)
    

In [4]:
# some test data to hack around with
test_file = "Assets\\DataShareArchive\\Test\\Clean\\p232_010.wav"
wav, rate = librosa.core.load(test_file)
fft = get_ft(wav)
print(fft.shape)

(768, 477)


In [26]:
# Creating data from clip wave files for adding to long data arrays

# Sample output is (samples, bins) all converted to magnitude
def get_samples(file):
    wav, rate = librosa.core.load(file)
    samples = abs(get_ft(wav).T) # organized as bins, frames so we need to transpose them to frames, bins
    return samples

In [45]:
def frames_file(data_path, max_samples):
    frames_file = data_path + "\\fsamples-" + str(max_samples)
    filename = os.fsdecode(frames_file)
    return filename

def targets_file(data_path, max_samples):
    targets_file = data_path + "\\ftargets-" + str(max_samples)
    filename = os.fsdecode(targets_file)
    return filename

# Iterate over clean & noisy folders to create frames and targets
def create_data(wav_root, data_path, max_samples = 10000):
    clean_dir = wav_root + "\\Clean\\"
    noisy_dir = wav_root + "\\Noisy\\"
    sample_index = 0
#    frames = np.memmap(frames_file(data_path, max_samples), mode='w+', dtype=DTYPE, shape=(max_samples,FFT_BINS,1))
#    targets = np.memmap(targets_file(data_path, max_samples), mode='w+', dtype=DTYPE, shape=(max_samples,FFT_BINS))
    frames = np.empty(dtype=DTYPE, shape=(max_samples,FFT_BINS,1))
    targets = np.empty(dtype=DTYPE, shape=(max_samples,FFT_BINS))
    file_list = os.listdir(clean_dir)
    file_index = 0
    while (sample_index < max_samples) and (file_index < len(file_list)) :
        file = file_list[file_index]
        filename = os.fsdecode(file)
        new_frames = get_samples(noisy_dir + file)
        max_step = min(new_frames.shape[0], max_samples-sample_index)
        frames[sample_index:sample_index+max_step,:,0] = new_frames[:max_step,:]
        new_targets = get_samples(clean_dir + file)
        targets[sample_index:sample_index+max_step,:] = new_targets[:max_step,:]
        sample_index += new_targets.shape[0]
        file_index += 1
    print("Reached sample # " + str(min(sample_index, max_samples)))
    return frames, targets


In [46]:
# Training data comes in at ~ 4 * 85K samples total (changed hop size so this will have changed)
f, t = create_data("Assets\\DataShareArchive\\Test", "f:\\Audiodata", max_samples=2000)

last frame  [[0.00290483 0.08943819 0.0277468  0.03653067 0.00570014 0.04190635
  0.05481525 0.00064881 0.01351169 0.02498227 0.0180965  0.0258149
  0.08558448 0.00326359 0.03970534 0.01028745 0.0360076  0.03015906
  0.00171996 0.05052185]]
last frame  [[0.05407887 0.04926184 0.0225051  0.04978212 0.00277668 0.02292588
  0.02362183 0.00177662 0.05377227 0.02528083 0.06121838 0.04865208
  0.01945572 0.02569535 0.0156109  0.02349244 0.01097936 0.00673081
  0.01102477 0.00298993]]
last frame  [[0.02338694 0.02601526 0.00943256 0.00870871 0.03182755 0.03828942
  0.00936001 0.00791292 0.00025157 0.02614782 0.01238661 0.00750359
  0.0012963  0.0124521  0.00298445 0.00780138 0.00216881 0.01003475
  0.00933276 0.00115248]]
Reached sample # 2000


In [90]:
print (f[20,200:210,0])
print (t[20,0:10])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [134]:
x = np.zeros((3,4,1))

In [135]:
t = np.ones((3,4))

In [136]:
x[:,:,0] = t

In [137]:
x


array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])